### ISSUE TITLE
Kanban feature request: drag and drop cards

### ISSUE THREAD

**Issue by jenandcleo** [cmheisel/kardboard#118]
I'm a bit OCD and fuss with the Kanban backlog constantly. I reorder. Add. Reorder. Change my mind. Reorder again. Remove stuff. Reorder again. To set the priority for cards requires opening each card and changing the number. If you add a new card and want to insert it between other cards, you have to reorder all cards.

Anyway, it would be nice if there was a way to drag/drop backlog cards to prioritize. The priority # automagically updates.

**Comment by cmheisel** [comment]
I definitely want to add this feature. I'm working on a v2 that builds on some of the learnings of v1 and will use a Bootstrap-powered responsive layout. As part of that I'll work drag-and-drop into it.
