### ISSUE TITLE
Funnel view with ordering

### ISSUE THREAD

**Issue by cmheisel** [cmheisel/kardboard#147]
Given one or more workflow states specified in configuration,
Provide a view of all the cards in that state, regardless of team
Default ordering to FIFO based on when the card entered that State
Allow for drag-and-drop reordering to override FIFO
Given a configured daily Throughput number, place backlog markers every N cards incremented by a day
Don't display backlog markers with weekend days, increment to the next work day

**Comment by cmheisel** [comment]
Posted this to a test server. Will do some manual testing and then bugfix/merge.

**Comment by cobbdb** [comment]
Wow this looks really great! Being able to view an approximate ordering on a single page could really help alleviate some of the mystery behind the otis queue. I have heard from several folks in QA that they are asked about queue order regularly. Thank you for remembering our work on this from hack day!
