### ISSUE TITLE
Add a link back to the team page

### ISSUE THREAD

**Issue by travismetcalf** [cmheisel/kardboard#61]
Hi Chris,

I'd like to request a feature that would improve the navigation/workflow of Kardboard.

I would like to see a link to my team's page from the card edit page (~/card/#####/edit/). Something like: "<-- back to Team 3"

When I am done editing a card and I have saved it my next desired action is to go back to my team's page so I can edit another card. 

Right now, I have two options to get back to my team's page:
1. I can use the back button in my browser and then click the browser's refresh button to see the changes I just made
2. I can click on the dashboard link the main navigation and then click on the team 3 link

Each of the above workflows are two clicks. My proposed workflow is one click.

The new functionality that allows us to represent the "blocked" card status on the virtual kandan board is great.

Thank you for all your extra effort to make Kardboard a great product for us to use.

**Comment by cmheisel** [comment]
Fixed in 7d5cb58c15739614dfcd3f51d9d0f4ab0b598aee
