### ISSUE TITLE
Add "Build to OTIS" option to ticket status

### ISSUE THREAD

**Issue by zmcghee** [cmheisel/kardboard#63]
A request from Sara: "Build to OTIS" is not represented in the Medley Dashboard.

**Comment by ghost** [comment]
What would be even better is if this just moved to that correct status based on the JIRA ticket status.

**Comment by maurackelly** [comment]
I am interested in this issue as well.

**Comment by cmheisel** [comment]
This is resolved via a config change on the server. Please follow #64 for the updates on the "What would be even better is if this just moved to that correct status based on the JIRA ticket status."
