### ISSUE TITLE
Implement jQuery date picker

### ISSUE THREAD

**Issue by nthdegreeburns** [cmheisel/kardboard#66]
I'd like to see the jQuery date picker added to the form entry fields.  I'm not sure if this feature is relevant anymore now that JIRA auto updates the start dates for milestones.

**Comment by cmheisel** [comment]
Feel free to fork it, work up a branch and send it over!

**Comment by nthdegreeburns** [comment]
Is this a valid issue, though?  Does JIRA always override the date functionality in the admin?
